global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'flask-api'
    static_configs:
      - targets: ['host.docker.internal:5000']
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'localhost:9093'

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'flask-api'
    static_configs:
      - targets: ['localhost:5000']
